#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for AT-commands script, atc
MAINTAINER:=Henrik Ginstmark <henrik@ginstmark.se>
PKG_VERSION:=2023.08.28
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
